
export const bVaraABI = [
  { type: "error", name: "InsufficientAllowance", inputs: [] },
  { type: "error", name: "InsufficientBalance", inputs: [] },
  { type: "error", name: "NonWhiteListed", inputs: [] },
  { type: "error", name: "VestingPositionAlreadyExists", inputs: [] },
  {
    type: "error",
    name: "VestingPositionNotFound",
    inputs: [
      { type: "address", name: "user", internalType: "address" },
      { type: "uint256", name: "vestId", internalType: "uint256" },
    ],
  },
  {
    type: "event",
    name: "Approval",
    inputs: [
      { type: "address", name: "owner", internalType: "address", indexed: true },
      { type: "address", name: "spender", internalType: "address", indexed: true },
      { type: "uint256", name: "value", internalType: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Exit",
    inputs: [
      { type: "address", name: "_addr", internalType: "address", indexed: true },
      { type: "uint256", name: "_vestID", internalType: "uint256", indexed: false },
      { type: "uint256", name: "_amount", internalType: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Initialized",
    inputs: [{ type: "uint8", name: "version", internalType: "uint8", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "MessageFailed",
    inputs: [
      { type: "uint16", name: "_srcChainId", internalType: "uint16", indexed: false },
      { type: "bytes", name: "_srcAddress", internalType: "bytes", indexed: false },
      { type: "uint64", name: "_nonce", internalType: "uint64", indexed: false },
      { type: "bytes", name: "_payload", internalType: "bytes", indexed: false },
      { type: "bytes", name: "_reason", internalType: "bytes", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "NewVest",
    inputs: [
      { type: "address", name: "_addr", internalType: "address", indexed: true },
      { type: "uint256", name: "_vestID", internalType: "uint256", indexed: false },
      { type: "uint256", name: "_amount", internalType: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      { type: "address", name: "previousOwner", internalType: "address", indexed: true },
      { type: "address", name: "newOwner", internalType: "address", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ReceiveFromChain",
    inputs: [
      { type: "uint16", name: "_srcChainId", internalType: "uint16", indexed: true },
      { type: "address", name: "_to", internalType: "address", indexed: true },
      { type: "uint256", name: "_amount", internalType: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Redeemed",
    inputs: [
      { type: "address", name: "_addr", internalType: "address", indexed: true },
      { type: "uint256", name: "vestID", internalType: "uint256", indexed: false },
      { type: "uint256", name: "_amount", internalType: "uint256", indexed: false },
      { type: "uint256", name: "_redeemAmount", internalType: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RetryMessageSuccess",
    inputs: [
      { type: "uint16", name: "_srcChainId", internalType: "uint16", indexed: false },
      { type: "bytes", name: "_srcAddress", internalType: "bytes", indexed: false },
      { type: "uint64", name: "_nonce", internalType: "uint64", indexed: false },
      { type: "bytes32", name: "_payloadHash", internalType: "bytes32", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SendToChain",
    inputs: [
      { type: "uint16", name: "_dstChainId", internalType: "uint16", indexed: true },
      { type: "address", name: "_from", internalType: "address", indexed: true },
      { type: "bytes", name: "_toAddress", internalType: "bytes", indexed: false },
      { type: "uint256", name: "_amount", internalType: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetMinDstGas",
    inputs: [
      { type: "uint16", name: "_dstChainId", internalType: "uint16", indexed: false },
      { type: "uint16", name: "_type", internalType: "uint16", indexed: false },
      { type: "uint256", name: "_minDstGas", internalType: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetPrecrime",
    inputs: [{ type: "address", name: "precrime", internalType: "address", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetTrustedRemote",
    inputs: [
      { type: "uint16", name: "_remoteChainId", internalType: "uint16", indexed: false },
      { type: "bytes", name: "_path", internalType: "bytes", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetTrustedRemoteAddress",
    inputs: [
      { type: "uint16", name: "_remoteChainId", internalType: "uint16", indexed: false },
      { type: "bytes", name: "_remoteAddress", internalType: "bytes", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetUseCustomAdapterParams",
    inputs: [
      { type: "bool", name: "_useCustomAdapterParams", internalType: "bool", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Transfer",
    inputs: [
      { type: "address", name: "from", internalType: "address", indexed: true },
      { type: "address", name: "to", internalType: "address", indexed: true },
      { type: "uint256", name: "value", internalType: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "WhiteList",
    inputs: [
      { type: "address", name: "_addr", internalType: "address", indexed: true },
      { type: "bool", name: "_status", internalType: "bool", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "DEFAULT_PAYLOAD_SIZE_LIMIT",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "NO_EXTRA_GAS",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint16", name: "", internalType: "uint16" }],
    name: "PT_SEND",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "allowance",
    inputs: [
      { type: "address", name: "owner", internalType: "address" },
      { type: "address", name: "spender", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "approve",
    inputs: [
      { type: "address", name: "spender", internalType: "address" },
      { type: "uint256", name: "amount", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "contract ERC20" }],
    name: "asset",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "balanceOf",
    inputs: [{ type: "address", name: "account", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "balanceOfVestId",
    inputs: [
      { type: "address", name: "user", internalType: "address" },
      { type: "uint256", name: "vestID", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "cancelVest",
    inputs: [{ type: "uint256", name: "vestID", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "circulatingSupply",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "uint256", name: "tokenId", internalType: "uint256" }],
    name: "convertToVe",
    inputs: [{ type: "uint256", name: "_amount", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint8", name: "", internalType: "uint8" }],
    name: "decimals",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "decreaseAllowance",
    inputs: [
      { type: "address", name: "spender", internalType: "address" },
      { type: "uint256", name: "subtractedValue", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "uint256", name: "nativeFee", internalType: "uint256" },
      { type: "uint256", name: "zroFee", internalType: "uint256" },
    ],
    name: "estimateSendFee",
    inputs: [
      { type: "uint16", name: "_dstChainId", internalType: "uint16" },
      { type: "bytes", name: "_toAddress", internalType: "bytes" },
      { type: "uint256", name: "_amount", internalType: "uint256" },
      { type: "bool", name: "_useZro", internalType: "bool" },
      { type: "bytes", name: "_adapterParams", internalType: "bytes" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bytes32", name: "", internalType: "bytes32" }],
    name: "failedMessages",
    inputs: [
      { type: "uint16", name: "", internalType: "uint16" },
      { type: "bytes", name: "", internalType: "bytes" },
      { type: "uint64", name: "", internalType: "uint64" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "forceResumeReceive",
    inputs: [
      { type: "uint16", name: "_srcChainId", internalType: "uint16" },
      { type: "bytes", name: "_srcAddress", internalType: "bytes" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "tuple[]",
        name: "",
        internalType: "struct bVaraImplementation.VestPosition[]",
        components: [
          { type: "uint256", name: "amount", internalType: "uint256" },
          { type: "uint256", name: "start", internalType: "uint256" },
          { type: "uint256", name: "maxEnd", internalType: "uint256" },
          { type: "uint256", name: "vestID", internalType: "uint256" },
          { type: "uint256", name: "exitIn", internalType: "uint256" },
        ],
      },
    ],
    name: "getAllVestInfo",
    inputs: [{ type: "address", name: "user", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bytes", name: "", internalType: "bytes" }],
    name: "getConfig",
    inputs: [
      { type: "uint16", name: "_version", internalType: "uint16" },
      { type: "uint16", name: "_chainId", internalType: "uint16" },
      { type: "address", name: "", internalType: "address" },
      { type: "uint256", name: "_configType", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bytes", name: "", internalType: "bytes" }],
    name: "getTrustedRemoteAddress",
    inputs: [{ type: "uint16", name: "_remoteChainId", internalType: "uint16" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "tuple",
        name: "",
        internalType: "struct bVaraImplementation.VestPosition",
        components: [
          { type: "uint256", name: "amount", internalType: "uint256" },
          { type: "uint256", name: "start", internalType: "uint256" },
          { type: "uint256", name: "maxEnd", internalType: "uint256" },
          { type: "uint256", name: "vestID", internalType: "uint256" },
          { type: "uint256", name: "exitIn", internalType: "uint256" },
        ],
      },
    ],
    name: "getVestInfo",
    inputs: [
      { type: "address", name: "user", internalType: "address" },
      { type: "uint256", name: "vestID", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "getVestLength",
    inputs: [{ type: "address", name: "user", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "increaseAllowance",
    inputs: [
      { type: "address", name: "spender", internalType: "address" },
      { type: "uint256", name: "addedValue", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "isTrustedRemote",
    inputs: [
      { type: "uint16", name: "_srcChainId", internalType: "uint16" },
      { type: "bytes", name: "_srcAddress", internalType: "bytes" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "lastMint",
    inputs: [{ type: "address", name: "", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "address", name: "", internalType: "contract ILayerZeroEndpointUpgradeable" },
    ],
    name: "lzEndpoint",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "lzReceive",
    inputs: [
      { type: "uint16", name: "_srcChainId", internalType: "uint16" },
      { type: "bytes", name: "_srcAddress", internalType: "bytes" },
      { type: "uint64", name: "_nonce", internalType: "uint64" },
      { type: "bytes", name: "_payload", internalType: "bytes" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "maxPenaltyPct",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "minDstGasLookup",
    inputs: [
      { type: "uint16", name: "", internalType: "uint16" },
      { type: "uint16", name: "", internalType: "uint16" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "minWithdrawDays",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "mint",
    inputs: [
      { type: "address", name: "_to", internalType: "address" },
      { type: "uint256", name: "_amount", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "string", name: "", internalType: "string" }],
    name: "name",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "nonblockingLzReceive",
    inputs: [
      { type: "uint16", name: "_srcChainId", internalType: "uint16" },
      { type: "bytes", name: "_srcAddress", internalType: "bytes" },
      { type: "uint64", name: "_nonce", internalType: "uint64" },
      { type: "bytes", name: "_payload", internalType: "bytes" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "owner",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "payloadSizeLimitLookup",
    inputs: [{ type: "uint16", name: "", internalType: "uint16" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "uint256", name: "_received", internalType: "uint256" },
      { type: "uint256", name: "_pct", internalType: "uint256" },
    ],
    name: "penalty",
    inputs: [
      { type: "uint256", name: "timestamp", internalType: "uint256" },
      { type: "uint256", name: "vestEndAt", internalType: "uint256" },
      { type: "uint256", name: "_amount", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "precrime",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [
      { type: "uint256", name: "_received", internalType: "uint256" },
      { type: "uint256", name: "_pct", internalType: "uint256" },
    ],
    name: "redeem",
    inputs: [{ type: "uint256", name: "vestID", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "renounceOwnership",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "payable",
    outputs: [],
    name: "retryMessage",
    inputs: [
      { type: "uint16", name: "_srcChainId", internalType: "uint16" },
      { type: "bytes", name: "_srcAddress", internalType: "bytes" },
      { type: "uint64", name: "_nonce", internalType: "uint64" },
      { type: "bytes", name: "_payload", internalType: "bytes" },
    ],
  },
  {
    type: "function",
    stateMutability: "payable",
    outputs: [],
    name: "sendFrom",
    inputs: [
      { type: "address", name: "_from", internalType: "address" },
      { type: "uint16", name: "_dstChainId", internalType: "uint16" },
      { type: "bytes", name: "_toAddress", internalType: "bytes" },
      { type: "uint256", name: "_amount", internalType: "uint256" },
      { type: "address", name: "_refundAddress", internalType: "address payable" },
      { type: "address", name: "_zroPaymentAddress", internalType: "address" },
      { type: "bytes", name: "_adapterParams", internalType: "bytes" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setConfig",
    inputs: [
      { type: "uint16", name: "_version", internalType: "uint16" },
      { type: "uint16", name: "_chainId", internalType: "uint16" },
      { type: "uint256", name: "_configType", internalType: "uint256" },
      { type: "bytes", name: "_config", internalType: "bytes" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setEndpoint",
    inputs: [{ type: "address", name: "_endpoint", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setMinDstGas",
    inputs: [
      { type: "uint16", name: "_dstChainId", internalType: "uint16" },
      { type: "uint16", name: "_packetType", internalType: "uint16" },
      { type: "uint256", name: "_minGas", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setPayloadSizeLimit",
    inputs: [
      { type: "uint16", name: "_dstChainId", internalType: "uint16" },
      { type: "uint256", name: "_size", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setPrecrime",
    inputs: [{ type: "address", name: "_precrime", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setReceiveVersion",
    inputs: [{ type: "uint16", name: "_version", internalType: "uint16" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setSendVersion",
    inputs: [{ type: "uint16", name: "_version", internalType: "uint16" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setTrustedRemote",
    inputs: [
      { type: "uint16", name: "_srcChainId", internalType: "uint16" },
      { type: "bytes", name: "_path", internalType: "bytes" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setTrustedRemoteAddress",
    inputs: [
      { type: "uint16", name: "_remoteChainId", internalType: "uint16" },
      { type: "bytes", name: "_remoteAddress", internalType: "bytes" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setUseCustomAdapterParams",
    inputs: [{ type: "bool", name: "_useCustomAdapterParams", internalType: "bool" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setWhitelist",
    inputs: [
      { type: "address", name: "_addr", internalType: "address" },
      { type: "bool", name: "_status", internalType: "bool" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setWithdrawalWindow",
    inputs: [{ type: "uint256", name: "_withdrawalWindow", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "supportsInterface",
    inputs: [{ type: "bytes4", name: "interfaceId", internalType: "bytes4" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "string", name: "", internalType: "string" }],
    name: "symbol",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "token",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "totalSupply",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "transfer",
    inputs: [
      { type: "address", name: "to", internalType: "address" },
      { type: "uint256", name: "amount", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "transferFrom",
    inputs: [
      { type: "address", name: "from", internalType: "address" },
      { type: "address", name: "to", internalType: "address" },
      { type: "uint256", name: "amount", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "transferOwnership",
    inputs: [{ type: "address", name: "newOwner", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bytes", name: "", internalType: "bytes" }],
    name: "trustedRemoteLookup",
    inputs: [{ type: "uint16", name: "", internalType: "uint16" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "useCustomAdapterParams",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "contract IVotingEscrow" }],
    name: "ve",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "uint256", name: "vestID", internalType: "uint256" }],
    name: "vest",
    inputs: [{ type: "uint256", name: "_amount", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "uint256", name: "amount", internalType: "uint256" },
      { type: "uint256", name: "start", internalType: "uint256" },
      { type: "uint256", name: "maxEnd", internalType: "uint256" },
      { type: "uint256", name: "vestID", internalType: "uint256" },
      { type: "uint256", name: "exitIn", internalType: "uint256" },
    ],
    name: "vestInfo",
    inputs: [
      { type: "address", name: "", internalType: "address" },
      { type: "uint256", name: "", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "whiteList",
    inputs: [{ type: "address", name: "", internalType: "address" }],
  },
] as const;